import type { Vehicle } from "../types";

export const VEHICLES: Vehicle[] = [
  {
    id: "econoline-15",
    image: "https://images.unsplash.com/photo-1675727410855-225534c6a781?auto=format&fit=crop&w=800&q=70",
    name: "Econoline 15 Passenger Van",
    similarTo: "Econoline 15 Passenger Van",
    vClass: "Van",
    doors: 3,
    seats: 15,
    baggage: 4,
    dailyRate: 200,
    deposit: 250,
    distancePerDay: 100,
    instantBooking: true,
    unitsLeft: 2,
  },
  {
    id: "full-size-suv",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=70",
    name: "Full size SUV",
    similarTo: "Ford Expedition or similar",
    vClass: "SUV",
    doors: 4,
    seats: 8,
    baggage: 1,
    dailyRate: 100,
    deposit: 250,
    distancePerDay: 100,
    instantBooking: true,
    unitsLeft: 2,
  },
  {
    id: "standard-suv",
    image: "https://images.unsplash.com/photo-1559038465-e0ca2910a5b1?auto=format&fit=crop&w=800&q=70",
    name: "Standard SUV",
    similarTo: "Ford Explorer or similar",
    vClass: "SUV",
    doors: 4,
    seats: 5,
    baggage: 3,
    dailyRate: 70,
    deposit: 250,
    distancePerDay: 100,
    instantBooking: true,
    unitsLeft: 4,
  },
  {
    id: "intermediate-sedan",
    image: "https://images.unsplash.com/photo-1605806678127-c5b0769d499f?auto=format&fit=crop&w=800&q=70",
    name: "Intermediate Sedan",
    similarTo: "Toyota Corolla or similar",
    vClass: "Sedan",
    doors: 4,
    seats: 5,
    baggage: 2,
    dailyRate: 45,
    deposit: 200,
    distancePerDay: 150,
    instantBooking: true,
    unitsLeft: 6,
  },
  {
    id: "economy",
    image: "https://images.unsplash.com/photo-1564988190211-cfee63481d3a?auto=format&fit=crop&w=800&q=70",
    name: "Economy",
    similarTo: "Kia Rio or similar",
    vClass: "Economy",
    doors: 4,
    seats: 5,
    baggage: 1,
    dailyRate: 35,
    deposit: 200,
    distancePerDay: 150,
    instantBooking: false,
    unitsLeft: 3,
  },
];

export function getVehicleById(id: string | null | undefined): Vehicle | undefined {
  if (!id) return undefined;
  return VEHICLES.find((v) => v.id === id);
}
